language: node_js
node_js:
  - "8.9.4"
services:
  - docker
script:
  - npm install
  - npm install coveralls
  - npm test --coverage
deploy:
  - docker build -t sparatan/yummypi .
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sparatan/yummypi
